#!/bin/bash

FINDALL=FALSE

#
# Process all options
#

while :
do
	case $1 in
		-a)	FINDALL=TRUE
			shift
			;;

		-h)	echo "Usage: $0 [-a] filenames"	
			exit 0
			;;
		
		*) 	break
			;;
	esac
done

#
# Check all files from  the command line
# 

for file in "$@"
do
	#
	# If file is a pathname, search the path and verify not a directory and  is executable
	#

	if [[ "$file"  = */* ]]
	then

		if [ -d "$file" ]
		then
			echo "$file NOT FOUND (this is a directory)"
			break
		fi
# can I get rid of  the -e?
		if [ -e "$file" -a -x "$file" ]
		then
			echo $file
		else
			echo "$file NOT FOUND"
		fi	
	
	#
	# File is not a pathname.  Search  the items on the path in order
	#
	
	else
		FOUND=FALSE
		DIRECTORY=FALSE

		export PATH
		pathsToSearch=$(echo $PATH  | sed -e 's/^:/.:/' -e 's/::/:.:/' -e 's/:$/:./' -e 's/:/ /g')
		for path in $pathsToSearch

		do
			if [ -x "$path/$file" -a ! -d "$path/file" ]
			then
				echo "$path/$file"
				FOUND="TRUE" 

				#
				# File has been found. Break if only finding one				#

				if [ $FINDALL = "FALSE" ]
				then
					break
				fi
			fi
		done

		#
		# Report test results
		#
		
		if [ $FOUND = "FALSE" ]
         	then     
			echo $file NOT FOUND
          	fi
	fi
done

